### ISSUE TITLE
Just saying thanks!

### ISSUE THREAD

**Issue by jeromedalbert** [haya14busa/vim-textobj-function-syntax#1]
This plugin is a lifesaver!

For months I could not find any Vim text object plugin to handle JavaScript ES2015 methods. There are plenty of plugins to handle old school `function abc() { ... }`s, but not `abc() { ... }` inside a class. I am not a frontend developer, but I edit modern JS files from time to time, and this was sorely needed.

I don't know what frontend Vimmers use, but with this plugin combined with the [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) syntax file, I can now use `yaf`, `daf`, `cif` etc to manipulate a method. 👍

**Comment by jeromedalbert** [comment]
PS: I am still on the lookout for a true JS method text object, so that Vim can distinguish between an anonymous function and an actual method. In the meantime I'll keep using this very useful plugin.

**Comment by haya14busa** [comment]
Thank you for your feedback! :+1:

**Comment by t9md** [comment]
Big-win of this package's general-purpose-ness, language-agnostics 👍 🎉
